# Generated by Django 3.2.5 on 2021-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Your city', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='house_number',
            field=models.CharField(default='Your house', max_length=60),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(default='Your street', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='zip_code',
            field=models.CharField(default='Your zip', max_length=60),
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(default='Your city', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='house_number',
            field=models.CharField(default='Your house', max_length=60),
        ),
        migrations.AddField(
            model_name='teacher',
            name='street',
            field=models.CharField(default='Your street', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zip_code',
            field=models.CharField(default='Your zip', max_length=60),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
